name: Build macOS App
on: [push, workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install pyinstaller soundcard soundfile requests numpy
        
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --name "AudioMirro" AudioMirro.py
        
    - name: Upload macOS app
      uses: actions/upload-artifact@v3
      with:
        name: AudioMirro-macOS
        path: dist/AudioMirro
