name: Build macOS App
on: [push, workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install pyinstaller opencv-python numpy mss websockets pillow
        
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --name "CueLens" CueLensResize.py
        
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: CueLens-macOS
        path: dist/CueLens
